enum_trailing_comma = true
fn_args_density = "Compressed"
fn_args_layout = "Block"
format_strings = false
ideal_width = 80
match_block_trailing_comma = true
match_wildcard_trailing_comma = true
max_width = 99
normalize_comments = false
reorder_imported_names = true
reorder_imports = true
report_fixme = "Always"
report_todo = "Always"
struct_lit_trailing_comma = "Vertical"
struct_trailing_comma = "Vertical"
where_trailing_comma = true
wrap_comments = true
write_mode = "Overwrite"
